### ISSUE TITLE
Use local eslint

### ISSUE THREAD

**Issue by nickdima** [bugsnag/depercolator#11]
Would be good if it could first check for eslint in the current project. The problem with global eslint is that when you'll call depercolator from a project's folder that has an eslint configuration it will complain about missing eslint plugins.
I could try making a PR if you think it's useful.

**Comment by wordofchristian** [comment]
Ok, try upgrading to v0.4.0

**Comment by wordofchristian** [comment]
Correction, v0.4.0 has a broken install process. use v0.4.1

**Comment by nickdima** [comment]
Should it work also as a local dependency? I didn't investigate to much but at a first try it doesn't seem to. This is the stack trace:

```
/my_project/node_modules/shelljs/src/common.js:401
      if (config.fatal) throw e;
                        ^

Error: exec: internal error
    at Object.error (/my_project/node_modules/shelljs/src/common.js:130:27)
    at Object._exec (/my_project/node_modules/shelljs/src/exec.js:292:12)
    at Object.exec (/my_project/node_modules/shelljs/src/common.js:334:23)
    at Command.processFile (/my_project/node_modules/depercolator/dist/index.js:117:44)
    at Command.listener (/my_project/node_modules/commander/index.js:301:8)
    at emitOne (events.js:96:13)
    at Command.emit (events.js:188:7)
    at Command.parseArgs (/my_project/node_modules/commander/index.js:617:12)
    at Command.parse (/my_project/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/my_project/node_modules/depercolator/dist/index.js:156:41)
```

**Comment by wordofchristian** [comment]
Hmm, It seems like it might be some error from either cjsx-transform or decaffeinate. I'm going look into it to see if there is something wrong with the error handling and maybe create a new issue, but in the meantime you might try opening `/my_project/node_modules/depercolator/dist/index.js` and commenting out line 47 which reads:

```js
_shelljs2.default.config.fatal = true;
```

and see what happens.

**Comment by wordofchristian** [comment]
It looks like this is caused by a parse error in the CJSX file. #18 should address this.
