### ISSUE TITLE
`ReferenceError: Unknown plugin` when installed via yarn

### ISSUE THREAD

**Issue by khalsah** [bugsnag/depercolator#19]
When installed via yarn, I am unable to get `depercolate` to run.

I believe the problem is the assumption of where that plugin will be installed: https://github.com/bugsnag/depercolator/blob/v0.4.1/src/index.js#L114

It looks like this might be fixed by the latest changes on master, but it's unclear when those will be released.

Yarn version: 0.24.6

```
/home/dev/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "/home/dev/.config/yarn/global/node_modules/depercolator/node_modules/babel-plugin-transform-react-createelement-to-jsx" specified in "base" at 0, attempted to resolve relative to "/home/dev/code/jsonapp"
    at /home/dev/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/home/dev/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/dev/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/home/dev/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/dev/.config/yarn/global/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/dev/.config/yarn/global/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/dev/.config/yarn/global/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Command.processFile (/home/dev/.config/yarn/global/node_modules/depercolator/dist/index.js:126:37)
    at Command.listener (/home/dev/.config/yarn/global/node_modules/commander/index.js:301:8)
```

**Comment by wordofchristian** [comment]
It should now be released `v0.4.2`

**Comment by khalsah** [comment]
Excellent, that works. Thanks!

**Comment by khalsah** [comment]
v0.4.3 appears to revert the change that made this work when using yarn.

yarn installs the `babel-plugin-transform-react-createelement-to-jsx` plugin to the root `node_modules` directory, while v0.4.3 assumes it will be installed under `node_modules/depercolator/node_modules`.

**Comment by wordofchristian** [comment]
Try with v0.4.4. Hopefully this resolves the issue once and for all for every case.
