### ISSUE TITLE
windows 10 powershell execution fatal error.

### ISSUE THREAD

**Issue by airtonix** [bugsnag/depercolator#6]
```
zenobius@DEV4 C:\Data\Projects\MAC\mac020 [develop*]
$ node -v
v6.10.0
zenobius@DEV4 C:\Data\Projects\MAC\mac020 [develop*]
$ depercolate
zenobius@DEV4 C:\Data\Projects\MAC\mac020 [develop*]
$ depercolate .\client\config\data\nav.js
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
C:\Program Files (x86)\Nodist\bin\node_modules\depercolator\node_modules\shelljs\src\common.js:401
      if (config.fatal) throw e;
                        ^

Error: exec: internal error
    at Object.error (C:\Program Files (x86)\Nodist\bin\node_modules\depercolator\node_modules\shelljs\src\common.js:130:27)
    at Object._exec (C:\Program Files (x86)\Nodist\bin\node_modules\depercolator\node_modules\shelljs\src\exec.js:292:12)
    at Object.exec (C:\Program Files (x86)\Nodist\bin\node_modules\depercolator\node_modules\shelljs\src\common.js:334:23)
    at Command.processFile (C:\Program Files (x86)\Nodist\bin\node_modules\depercolator\index.js:89:6)
    at Command.listener (C:\Program Files (x86)\Nodist\bin\node_modules\depercolator\node_modules\commander\index.js:301:8)
    at emitOne (events.js:96:13)
    at Command.emit (events.js:188:7)
    at Command.parseArgs (C:\Program Files (x86)\Nodist\bin\node_modules\depercolator\node_modules\commander\index.js:617:12)
    at Command.parse (C:\Program Files (x86)\Nodist\bin\node_modules\depercolator\node_modules\commander\index.js:458:21)
    at Object.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\depercolator\index.js:129:4)
zenobius@DEV4 C:\Data\Projects\MAC\mac020 [develop*]
```

**Comment by jmshal** [comment]
Looks like the classic space-in-a-path issue. Thanks Windows 😛 

https://github.com/bugsnag/depercolator/blob/master/index.js#L12

I'd be happy to submit a PR.

**Comment by wordofchristian** [comment]
Thx JM, all PRs are welcome in this house
